
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl CPMEVENTHANDLERABSTRACT
// ------------------------------
#ifndef CPMEVENTHANDLERABSTRACT_EXPORT_H
#define CPMEVENTHANDLERABSTRACT_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (CPMEVENTHANDLERABSTRACT_HAS_DLL)
#  define CPMEVENTHANDLERABSTRACT_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && CPMEVENTHANDLERABSTRACT_HAS_DLL */

#if !defined (CPMEVENTHANDLERABSTRACT_HAS_DLL)
#  define CPMEVENTHANDLERABSTRACT_HAS_DLL 1
#endif /* ! CPMEVENTHANDLERABSTRACT_HAS_DLL */

#if defined (CPMEVENTHANDLERABSTRACT_HAS_DLL) && (CPMEVENTHANDLERABSTRACT_HAS_DLL == 1)
#  if defined (CPMEVENTHANDLERABSTRACT_BUILD_DLL)
#    define CPMEVENTHANDLERABSTRACT_Export ACE_Proper_Export_Flag
#    define CPMEVENTHANDLERABSTRACT_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define CPMEVENTHANDLERABSTRACT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* CPMEVENTHANDLERABSTRACT_BUILD_DLL */
#    define CPMEVENTHANDLERABSTRACT_Export ACE_Proper_Import_Flag
#    define CPMEVENTHANDLERABSTRACT_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define CPMEVENTHANDLERABSTRACT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* CPMEVENTHANDLERABSTRACT_BUILD_DLL */
#else /* CPMEVENTHANDLERABSTRACT_HAS_DLL == 1 */
#  define CPMEVENTHANDLERABSTRACT_Export
#  define CPMEVENTHANDLERABSTRACT_SINGLETON_DECLARATION(T)
#  define CPMEVENTHANDLERABSTRACT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* CPMEVENTHANDLERABSTRACT_HAS_DLL == 1 */

// Set CPMEVENTHANDLERABSTRACT_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (CPMEVENTHANDLERABSTRACT_NTRACE)
#  if (ACE_NTRACE == 1)
#    define CPMEVENTHANDLERABSTRACT_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define CPMEVENTHANDLERABSTRACT_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !CPMEVENTHANDLERABSTRACT_NTRACE */

#if (CPMEVENTHANDLERABSTRACT_NTRACE == 1)
#  define CPMEVENTHANDLERABSTRACT_TRACE(X)
#else /* (CPMEVENTHANDLERABSTRACT_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define CPMEVENTHANDLERABSTRACT_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (CPMEVENTHANDLERABSTRACT_NTRACE == 1) */

#endif /* CPMEVENTHANDLERABSTRACT_EXPORT_H */

// End of auto generated file.
