
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl CPMEVENTHANDLERMGR
// ------------------------------
#ifndef CPMEVENTHANDLERMGR_EXPORT_H
#define CPMEVENTHANDLERMGR_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (CPMEVENTHANDLERMGR_HAS_DLL)
#  define CPMEVENTHANDLERMGR_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && CPMEVENTHANDLERMGR_HAS_DLL */

#if !defined (CPMEVENTHANDLERMGR_HAS_DLL)
#  define CPMEVENTHANDLERMGR_HAS_DLL 1
#endif /* ! CPMEVENTHANDLERMGR_HAS_DLL */

#if defined (CPMEVENTHANDLERMGR_HAS_DLL) && (CPMEVENTHANDLERMGR_HAS_DLL == 1)
#  if defined (CPMEVENTHANDLERMGR_BUILD_DLL)
#    define CPMEVENTHANDLERMGR_Export ACE_Proper_Export_Flag
#    define CPMEVENTHANDLERMGR_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define CPMEVENTHANDLERMGR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* CPMEVENTHANDLERMGR_BUILD_DLL */
#    define CPMEVENTHANDLERMGR_Export ACE_Proper_Import_Flag
#    define CPMEVENTHANDLERMGR_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define CPMEVENTHANDLERMGR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* CPMEVENTHANDLERMGR_BUILD_DLL */
#else /* CPMEVENTHANDLERMGR_HAS_DLL == 1 */
#  define CPMEVENTHANDLERMGR_Export
#  define CPMEVENTHANDLERMGR_SINGLETON_DECLARATION(T)
#  define CPMEVENTHANDLERMGR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* CPMEVENTHANDLERMGR_HAS_DLL == 1 */

// Set CPMEVENTHANDLERMGR_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (CPMEVENTHANDLERMGR_NTRACE)
#  if (ACE_NTRACE == 1)
#    define CPMEVENTHANDLERMGR_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define CPMEVENTHANDLERMGR_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !CPMEVENTHANDLERMGR_NTRACE */

#if (CPMEVENTHANDLERMGR_NTRACE == 1)
#  define CPMEVENTHANDLERMGR_TRACE(X)
#else /* (CPMEVENTHANDLERMGR_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define CPMEVENTHANDLERMGR_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (CPMEVENTHANDLERMGR_NTRACE == 1) */

#endif /* CPMEVENTHANDLERMGR_EXPORT_H */

// End of auto generated file.
