// -*- C++ -*- generated by wxGlade 0.6.5 on Tue Nov 20 07:47:34 2012 from "C:\Projects\CPM\core\CPMG\src\CPMG.wxg"

#include <wx/wx.h>
#include <wx/image.h>

#ifndef NODEDLG_H
#define NODEDLG_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class NodeDlg: public wxDialog {
public:
    // begin wxGlade: NodeDlg::ids
    // end wxGlade

    NodeDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    wxString node_id() { return text_ctrl_node->GetValue(); }

private:
    // begin wxGlade: NodeDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: NodeDlg::attributes
    wxStaticText* label_node;
    wxTextCtrl* text_ctrl_node;
    wxButton* button_ok;
    wxButton* button_cancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void on_button_ok(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void on_button_cancel(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // NODEDLG_H
