// -*- C++ -*- generated by wxGlade 0.6.5 on Tue Nov 20 07:47:34 2012 from "C:\Projects\CPM\core\CPMG\src\CPMG.wxg"

#include "ACEWin64Warnings/BeginSuppressWarnings.h"
#include "ace/ACE.h" // to avoid problem with mode_t (wxWidgets\2.9.4\include\wx\filefn.h: line 82: wxNEEDS_MODE_T)
#include "ACEWin64Warnings/EndSuppressWarnings.h"

#include "NodeDlg.h"
#include "wxids.h"

// begin wxGlade: ::extracode
// end wxGlade

#define wxTHICK_FRAME wxRESIZE_BORDER


NodeDlg::NodeDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxTHICK_FRAME)
{
    style;

    // begin wxGlade: NodeDlg::NodeDlg
    label_node = new wxStaticText(this, wxID_ANY, _("Node ID:"));
    text_ctrl_node = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    button_ok = new wxButton(this, wxID_HIGHEST + wxID_button_node_ok, _("Ok"));
    button_cancel = new wxButton(this, wxID_HIGHEST + wxID_button_node_cancel, _("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(NodeDlg, wxDialog)
    // begin wxGlade: NodeDlg::event_table
    EVT_BUTTON(wxID_HIGHEST + wxID_button_node_ok, NodeDlg::on_button_ok)
    EVT_BUTTON(wxID_HIGHEST + wxID_button_node_cancel, NodeDlg::on_button_cancel)
    // end wxGlade
END_EVENT_TABLE();


void NodeDlg::on_button_ok(wxCommandEvent &)
{
    this->EndModal(wxID_OK);
}


void NodeDlg::on_button_cancel(wxCommandEvent &)
{
    this->EndModal(wxID_CANCEL);
}


// wxGlade: add NodeDlg event handlers


void NodeDlg::set_properties()
{
    // begin wxGlade: NodeDlg::set_properties
    SetTitle(_("Node"));
    // end wxGlade
}


void NodeDlg::do_layout()
{
    // begin wxGlade: NodeDlg::do_layout
    wxBoxSizer* sizer_17 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_21 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_20 = new wxBoxSizer(wxHORIZONTAL);
    sizer_20->Add(label_node, 0, wxALL, 10);
    sizer_20->Add(text_ctrl_node, 1, wxALL, 10);
    sizer_17->Add(sizer_20, 0, wxEXPAND, 0);
    sizer_21->Add(button_ok, 0, wxALL, 3);
    sizer_21->Add(button_cancel, 0, wxALL, 3);
    sizer_17->Add(sizer_21, 0, wxALL|wxALIGN_BOTTOM|wxALIGN_CENTER_HORIZONTAL, 5);
    SetSizer(sizer_17);
    sizer_17->Fit(this);
    Layout();
    // end wxGlade
}

