// -*- C++ -*- generated by wxGlade 0.6.5 on Fri Nov 16 12:56:23 2012 from "C:\Projects\CPM\core\CPMG\src\CPMG.wxg"

#include <wx/wx.h>
#include <wx/image.h>
#include <string>

#ifndef PROCESSDLG_H
#define PROCESSDLG_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class ProcessDlg: public wxDialog {
public:
    // begin wxGlade: ProcessDlg::ids
    // end wxGlade

    ProcessDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    std::string process_id() { return text_ctrl_process_id->GetValue().ToStdString(); }
    std::string env_var_id() { return text_ctrl_env_var_id->GetValue().ToStdString(); }
    std::string module_name() { return text_ctrl_module_name->GetValue().ToStdString(); }
    std::string port() { return text_ctrl_port->GetValue().ToStdString(); }
    bool enabled() { return checkbox_enabled->GetValue(); }

private:
    // begin wxGlade: ProcessDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ProcessDlg::attributes
    wxStaticText* label_process_id;
    wxTextCtrl* text_ctrl_process_id;
    wxStaticText* label_env_var_id;
    wxTextCtrl* text_ctrl_env_var_id;
    wxStaticText* label_module_name;
    wxTextCtrl* text_ctrl_module_name;
    wxStaticText* label_port;
    wxTextCtrl* text_ctrl_port;
    wxCheckBox* checkbox_enabled;
    wxButton* button_ok;
    wxButton* button_cancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void on_button_ok(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void on_button_cancel(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // PROCESSDLG_H
